---
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
name: Run unit tests

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-snowflake==1.3.0
    - name: Run tests
      run: |
        cd unit_testing_ci_exploration
        dbt deps
        echo "${PROFILES_YML}" > profiles.yml
        dbt test --select tag:unit-test
      env:
        PROFILES_YML: ${{ secrets.PROFILES_YML }}